services:
  server:
    image: kariukiantony/kilimboga-server:latest
    container_name: kilimboga-server
    ports:
      - "3000:3000"
    networks:
      - kilimboga

  client:
    image: kariukiantony/kilimboga-client:latest
    container_name: kilimboga-client
    ports:
      - "5173:5173"
    command: npm run dev
    networks:
      - kilimboga
    depends_on:
      - server

networks:
  kilimboga:
    driver: bridge